language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - liblapack-dev
        - clang-3.6
        - libhdf5-serial-dev
        - gfortran
        - g++-4.9
    env:
      - CXX_COMPILER='clang++-3.6'
      - PYTHON_VER='3.6'
      - C_COMPILER='clang-3.6'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Debug'
      - NAME='clang'
      - VERSION='3.6'

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n qforte python=$PYTHON_VER numpy cmake 
- source activate qforte
- python -V
- pyenv global system 3.6
- cd ${TRAVIS_BUILD_DIR}
- export CXX=${CXX_COMPILER}
- export CC=${C_COMPILER}
- export FC=${Fortran_COMPILER}
- export CTEST_OUTPUT_ON_FAILURE=1
- ${CXX_COMPILER} --version
- ${Fortran_COMPILER} --version
- ${C_COMPILER} --version
- cd ${HOME}/build/evangelistalab/qforte
- python setup compile
- ls -l
